[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/bioinfo_pipelines -ra"""


[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"